# This is a basic workflow to help you get started with Actions

name: Team build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn
          npx jetifier

      - name: Up version
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} yarn release

      - name: Build
        run: yarn build

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: test
          releaseNotesFile: CHANGELOG.md
          file: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: android/app/build/outputs/apk/release/app-release.apk
